on:
  push:
  pull_request:
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: ''
  
