on:
  push:
  pull_request:
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dante-ev/latex-action@latest
        with:
          root_file: cv.tex
      - uses: dante-ev/latex-action@latest
        with:
          root_file: cv_no_profilepic.tex
